{% set name = "shippinglabel" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/domdfcoding/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 17373b3863b9cafa4766d34ccb2e65028b6b2fe949ab820a72a312013c75b9a8
  patches:
    - patches/0001-removed-dependencies-from-the-conftest.patch

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<37]

requirements:
  build:
    - patch  # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - hatchling
    - hatch-requirements-txt
  run:
    - python
    - dist-meta >=0.1.2
    - dom-toml >=0.2.2
    - domdf-python-tools >=3.1.0
    - packaging >=20.9
    - typing-extensions >=3.7.4.3

test:
  source_files:
    - tests
  imports:
    - shippinglabel
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # ModuleNotFoundError: No module named 'apeye'
    - pytest -v -k "not (test_list_requirements)" tests
  requires:
    - pip
    - pytest >=6.0.0
    - coincidence >=0.2.0
    - consolekit >=1.1.2
    - requests >=2.25.1

about:
  home: https://github.com/domdfcoding/shippinglabel
  summary: Utilities for handling packages.
  license: MIT AND Apache-2.0
  license_family: MIT
  license_file:
    - LICENSE
    - shippinglabel/_vendor/trove_classifiers/LICENSE
  description: Utilities for handling packages.
  doc_url: https://shippinglabel.readthedocs.io
  dev_url: https://github.com/domdfcoding/shippinglabel

extra:
  recipe-maintainers:
    - domdfcoding